version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0
    restart: always
    ports:
      - '4003:27017'
    volumes:
      - ./data:/data/db
  api:
    container_name: api-container
    image: node:16-alpine3.14
    restart: always
    ports:
      - '4001:8001'
      - '4002:8002'
    working_dir: /usr/src/api
    command: sh -c "yarn install --prod && yarn debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/api
    volumes:
      - ./dist/:/usr/src/api/dist/
      - ./package.json:/usr/src/api/package.json
